# Dockerfile
# Use the official Node.js 16 image as the base image.
FROM node:16

# Create and set the working directory.
WORKDIR /usr/src/app

# Copy the package.json and package-lock.json to the working directory.
COPY package*.json ./

# Install dependencies.
RUN npm install

# Copy the rest of the application code to the working directory.
COPY . .

# Expose the port the app will run on.
EXPOSE 9001

# Command to run the application.
CMD ["node", "server.js"]
